### ISSUE TITLE
Value of empty summernote is not empty string

### ISSUE THREAD

**Issue by im1dermike** [summernote/angular-summernote#53] opened 2015-05-12 15:55 UTC
The value of a summernote model before entering text is an empty string as expected.  But if you enter text and then remove it, the value of the summernote model is `<br>`.  This ruins ngRequired.

Oddly enough, in my testing, if you type text into an empty summernote, then remove it, its value is `<br>`.  But if you add some hard returns to the empty summernote, then delete them, its value is an empty string.

**Comment by outsideris** [comment] 2015-05-14 03:49
Ok. I will test it.

**Comment by outsideris** [comment] 2015-05-18 19:23
I can't reproduce it.
Can you explain more detail with version of summernote and angular-summernote or browser you tested.

**Comment by im1dermike** [comment] 2015-05-18 19:51
Unfortunately, neither summernote nor your angular-summernote JS files supply a version.  summernote.js does supply `Date: 2015-04-29T19:41Z` for whatever that's worth.

Hopefully this screencast will help:  http://www.screencast.com/t/EchUew7sx3g

**Comment by outsideris** [comment] 2015-05-25 11:14
I will try to fix it if [summernote/#1097](https://github.com/summernote/summernote/pull/1097) is merged and released.

**Closed** 2015-07-03 12:19 UTC
